// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiduvcxmtzpwgwmtsmzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZHV2Y3htdHpwd2d3bXRzbXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTQ4NjQsImV4cCI6MjA2NDM5MDg2NH0.B08ldBYkO1NNpnAq6GinPWskUw9rreOee4S9RqPAu5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});